#!/bin/sh

# osd_cat options
POS=bottom      # top, middle or bottom
ALIGN=center    # left, center or right
OFFSET=60       # offset from the top or bottom
COLOR=pink      # white, blue, yellow, cyan, magenta, green, etc
MUTECOLOR=brown # color to use instead when muted
SHADOW=2        # offset of shadow, 0 for none
DELAY=1         # seconds to show the OSD
AGE=0           # seems broken :\
BARMODE=slider  # percentage or slider
FONT=-*-courier-*-r-*-*-32-*-*-*-*-*-*


BRIGHTNESS=$(cat /sys/class/backlight/radeon_bl0/brightness)

if [ "$1" = "up" ]; then
echo 200 > /sys/class/backlight/radeon_bl0/brightness
elif [ "$1" = "down" ]; then
xbacklight -dec 10 -time 200 -fps 25
else
    echo "Usage: $0 up|down|mute"
fi


killall osd_cat >/dev/null 2>&1   # if the -a switch worked, we wouldn't need this
osd_cat -p $POS -c $COLOR -s $SHADOW -a $AGE -d $DELAY -o $OFFSET -A $ALIGN \-b $BARMODE -P $BRIGHTNESS -f $FONT -l 1 -T "Brightness *: $BRIGHTNESS"
